Repository silverstripe/addons.silverstripe.org, pull requests merged in 2018-05, with the labels that each got.

#176 API Remove HelpfulRobot tasks and implementation in favour of silverstripe/moduleratings
  .gitignore
  .platform.yml
  README.md
  composer.json
  composer.lock
  mysite/_config/extensions.yml
  mysite/_config/jobs.yml
  mysite/code/crons/NightlyUpdatesCron.php
  mysite/code/dataobjects/Addon.php
  mysite/code/extensions/QueuedJobsAdminExtension.php
  mysite/code/services/AddonBuilder.php
  mysite/code/tasks/CacheHelpfulRobotDataTask.php
  mysite/tests/services/AddonBuilderTest.php
  themes/addons/templates/Includes/ModuleRatingVisual.ss
  themes/addons/templates/Layout/Addon.ss
Labels: change/major

#183 FIX: Fix font-loading on HTTPS
  themes/addons/css/addons.css
  themes/addons/less/base.less
Labels: change/patch

#181 Update "popular blacklist" to include all SS4 core modules
  mysite/code/controllers/HomeController.php
Labels: change/patch, type/bug

#184 FIX Do not specify protocol for Gravatar URL to allow HTTPS
  mysite/code/dataobjects/AddonAuthor.php
Labels: change/patch

#189 NEW Add JSON API to return rating metrics for modules
  README.md
  mysite/_config/routes.yml
  mysite/code/controllers/RatingApiController.php
  mysite/tests/Controllers/RatingApiControllerTest.php
  mysite/tests/Controllers/RatingApiControllerTest.yml
Labels: change/minor

#188 NEW Add Raygun monitoring integration
  composer.json
  composer.lock
Labels: change/minor

#194 NEW Adding capturing version information sent in headers as a metric
  mysite/code/controllers/ApiController.php
  mysite/code/dataobjects/ApiCallerVersions.php
  mysite/tests/Controllers/ApiControllerTest.php
Labels: affects/v4, change/minor

#195 NEW Update framework to 3.6.6
  composer.lock
Labels: type/enhancement
